### ISSUE TITLE
golang implementation for genact

### ISSUE THREAD

**Issue by chenjiandongx** [svenstaro/genact#133]
Hi, @svenstaro 

Thanks for your brilliant works. genact is an awesome project and I have ported the code to the Go language named oscar

here is the project link: https://github.com/chenjiandongx/oscar

Now I can take a rest and drink coffee seriously. lol 🐶

**Comment by svenstaro** [comment]
Well, that was certainly unexpected but really cool to see!

**Comment by chenjiandongx** [comment]
😁  ok, close this pr.
