### ISSUE TITLE
Feature request: exit after x amount of clusters

### ISSUE THREAD

**Issue by ColdEvul** [svenstaro/genact#137]
I love this little program it added some fun boot gibberish top a little fake program i am writing together. Provided a little screenshot from it below.

One thing i would love to have is a param similar to the `-s` that limits amount of blocks used instead of a set time.
This especially useful for the `botnet` or `downloading` simulations were you want it to stop after a set amount of gibberish.

![Screenshot from 2020-08-20 16-46-31](https://user-images.githubusercontent.com/13811113/90788108-bb017d00-e305-11ea-9867-2b9e2e528e10.png)

**Comment by svenstaro** [comment]
So you want to limit it after running a fixed number of modules?

**Comment by svenstaro** [comment]
I tried to implement your request as I understood it. Please give me feedback if that's what you wanted.

**Comment by ColdEvul** [comment]
Works exsact like I imagined it 
Thank you good sir!
