### ISSUE TITLE
Mac OSX binaries missing

### ISSUE THREAD

**Issue by tifa2UP** [svenstaro/genact#16]
It looks like the OSX binaries are missing from the releases page: https://github.com/svenstaro/genact/releases

**Comment by svenstaro** [comment]
I know. The problem exists because Travis has a giant backlog on OSX because of their outage yesterday. Check here: https://www.traviscistatus.com/

It should fix itself soon, hopefully. :)

**Comment by calpa** [comment]
Same here, waiting for your good news. @svenstaro

**Comment by tifa2UP** [comment]
Aha, thank you @svenstaro! Keep us in the loop.

**Comment by svenstaro** [comment]
Will do. If you're on OSX, there are four other ways you can use for now:

1. Compile it yourself (it's really easy if you have Rust installed).
2. The WebAssembly version.
3. The Docker version.
4. The Windows version with wine.

If none of these are particularly appealing, I suppose we'll have to wait on Travis. :/

**Comment by dikyarga** [comment]
When I'm trying to ```cargo run``` or ```cargo install genact``` resulting the same, 
![screen shot 2018-01-18 at 17 57 43](https://user-images.githubusercontent.com/6753674/35095446-11a7b062-fc7b-11e7-8fdc-4a5fe9e36f9f.png)

**Comment by svenstaro** [comment]
Can you tell me the output of `rust --version` and `cargo --version`?

**Comment by lagwy** [comment]
It looks like Travis is working correctly now, but the binary isn't at releases page yet.

**Comment by svenstaro** [comment]
Travis is still catching up I'm afraid. It's going slowly.

**Comment by dikyarga** [comment]
```cargo --version```
cargo 0.20.0 (a60d185c8 2017-07-13)

```rustc -V```
rustc 1.19.0 (0ade33941 2017-07-17)

**Comment by svenstaro** [comment]
Those are too old I'm afraid. You should look into getting upgraded to latest stable (or perhaps just use rustup to make this process a lot easier).

**Comment by svenstaro** [comment]
This is now fixed \o/
