### ISSUE TITLE
Add some line bursting mode to bootlog

### ISSUE THREAD

**Issue by svenstaro** [svenstaro/genact#24]
It would be cool if the bootlog module behaved a bit more realistically in the way that it would sometimes burst a bunch of lines really quickly.

**Comment by briankabiro** [comment]
Hey, @svenstaro. Has this been taken up?

**Comment by svenstaro** [comment]
Nope, feel free to take a stab!

**Comment by svenstaro** [comment]
@briankabiro No problem! Glad to help.

Currently, the flow is like this:

    Print a random line from the input
    Sleep a random number of millis

It should be changed to be like this:

    Decide whether we should enter line bursting mode with a small chance (say 1/20)
         If in line bursting mode, quickly burst between 5 to 25 lines randomly with a very small sleep between them
         If not in line bursting mode, simple print a random line from the input
    Sleep a random number of millis

**Comment by briankabiro** [comment]
Thanks for the guidance. Will be raising a PR soon.

**Comment by briankabiro** [comment]
#35
