### ISSUE TITLE
Problem When Using Index.html

### ISSUE THREAD

**Issue by goodshibe20-cool** [svenstaro/genact#262]
When I Download The Genact-Master And Run The Index.html File Half Of The Webpage Is Black And The Other Side Is White
Please Fix This
Btw Im On Chromebook So That Might Explain The Problem

**Comment by svenstaro** [comment]
You have to host it using some kind of webserver. Why don't you just use the online version?

**Comment by svenstaro** [comment]
Reopen please if this remains a problem.
