### ISSUE TITLE
[suggestion] add ansible module

### ISSUE THREAD

**Issue by raspbeguy** [svenstaro/genact#301]
Running an average ansible playbook lakes a lots of outputs and takes a good amount of time.

That would make a great module IMHO.

**Comment by svenstaro** [comment]
Oh yeah that'd be great. Would you like to take a stab at it?

**Comment by raspbeguy** [comment]
Sadly I don't know Rust at all :(

**Comment by svenstaro** [comment]
I think genact would be a rather nice project to get started with. [Here](https://github.com/svenstaro/genact/blob/master/src/modules/composer.rs) is a module that I think would probably be rather good as a starting point for an Ansible module. Maybe give it a spin, it's good fun. :)
