### ISSUE TITLE
build-web generate a index file that resource path contains /genact

### ISSUE THREAD

**Issue by Tiny-Wei** [svenstaro/genact#375]
When I use `trunk build --release` build a web page, The resource path of the index.html file contains /genact.

**Comment by svenstaro** [comment]
I don't really understand what you want here. Do you want something changed?

**Comment by Tiny-Wei** [comment]
generated index.html contains 
``` <link rel="preload" href="/genact/genact-748f4159b5243148_bg.wasm" as="fetch" type="application/wasm" crossorigin=""> ```
it's a wrong directory, should be:
``` <link rel="preload" href="/genact-748f4159b5243148_bg.wasm" as="fetch" type="application/wasm" crossorigin=""> ```
i changed Trunk.toml make it work.
