### ISSUE TITLE
Investigate compressing data files

### ISSUE THREAD

**Issue by svenstaro** [svenstaro/genact#38]
Maybe I can cut the size down by compressing stuff in `data/` during build time (with build.rs) and then decompressing it during runtime. Gotta investigate.

**Comment by Byron-TW** [comment]
Something that could make this transparent is to use `upx` to pack the whole binary. This slows down startup time (due to decompression), but it's as easy as `upx <binary>` to usually shrink the file to 1/3rd of its size.

**Comment by svenstaro** [comment]
I believe this won't actually compress the data files themselves and also upx doesn't work for the web. I'd like to have some macro compile time compression here optimally.

**Comment by svenstaro** [comment]
I'll use https://github.com/SOF3/include-flate for this.

**Comment by svenstaro** [comment]
I investigated this and turns out that using `upx --lzma` the resulting binary will actually be smaller than when using `include-flate`. It still buys a couple hundred KBs on wasm32 but I think at this point we should just rely on `wasm-opt` to become better over time.
