### ISSUE TITLE
About the unloading problem

### ISSUE THREAD

**Issue by Caipenghui** [svenstaro/genact#39]
If I don't want to use this software, how can I uninstall it?

**Comment by svenstaro** [comment]
Depends. How did you install it in the first place?

**Comment by Caipenghui** [comment]
Ok, my home is in China, my home is at 12:27. Utc + 8. You were different from us then? thank you

**Comment by Caipenghui** [comment]
You're supposed to be in the morning. Good morning.

**Comment by svenstaro** [comment]
Yes, indeed I am. Good morning. Can we consider this issue closed?

**Comment by Caipenghui** [comment]
Ok,You can.
