### ISSUE TITLE
Heads-up: FreeBSD port is on its way

### ISSUE THREAD

**Issue by 0mp** [svenstaro/genact#40]
FYI, genact is going to be included in the FreeBSD ports collection soon. 

The PR is available here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=228306

When it's pulled it will be able to install a prebuilt genact package with:

```
pkg install genact
```

Nice and easy. You can start generating nonsense in no time.

Cheers! 😄

**Comment by svenstaro** [comment]
Sweet! Would you for this to be included in the README?

**Comment by svenstaro** [comment]
Also, why is it a `games` port? This is a serious tool filling an important niche in corporate infrastructures.

**Comment by 0mp** [comment]
We should definitely included in the README.

It's in games because this is where all the important things go. Category `sysutils` didn't quite fit as it's for tools broken by design you have to use if genact is not available on the system. `deskutils` is described as  

> Things that used to be on deskutils the desktop before computers were invented.

which doesn't fit as well, obviously. `genact` is a revolutionary utility in that sense.

`x11` is inappropriate either since `genact` is a proper command-line tool without all those useless graphical bells and whistles.

Actually, we may try to propose a new `lifestyle` category. Here's a link to the procedure: https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/makefile-categories.html#proposing-categories

For the time being, however, `genact` is going to reign the kingdom of `games`.

**Comment by svenstaro** [comment]
Hahah ok fair enough. You wanna make a PR for the README?

**Comment by 0mp** [comment]
I'll submit one once the port makes it to the ports collection officially. 😄

**Comment by svenstaro** [comment]
Sounds fair. Closing.
