### ISSUE TITLE
[Feature Request] fill up screen on start

### ISSUE THREAD

**Issue by josherrickson** [svenstaro/genact#582]
Is there a way to have the first n lines printed immediately upon execution, so it appears that the activity is already in progress? I'd imagine something like setting any pauses to 0 for the first n lines of code.

**Comment by josherrickson** [comment]
I don't know Rust yet. If you could point me to where in the code to start looking, I could give it a shot.

**Comment by svenstaro** [comment]
I think the code should be fairly accessible for beginners! I'd start by looking here: https://github.com/svenstaro/genact/blob/master/src/io.rs#L11. We already have a `SPEED_FACTOR` there. We could add something like `QUICKSTART` (or better name) that would access a global counter if provided as a flag and if that counter is `> 0` then it would not sleep at all. This in turn would cause a good chunk of text to be printed without any delay. Should be a fairly low-touch change. What do you think?

**Comment by svenstaro** [comment]
Fixed by #583.
