### ISSUE TITLE
Terraform module hangs in the web version

### ISSUE THREAD

**Issue by taskinen** [svenstaro/genact#624]
The Terraform module hangs with the message "Acquiring state lock. This may take a few moments..." when accessed via the web version at https://svenstaro.github.io/genact/

The issue appears to be with the code, where the sleep command doesn't terminate:

```
print("Acquiring state lock. This may take a few moments...\r\n").await;
csleep(500).await;
```

Or could the problem lie with a subsequent operation that fails to execute?

The implementation of the sleep function is consistent with its use in other modules.

**Comment by svenstaro** [comment]
Oh no! Good catch. I can reproduce this on https://svenstaro.github.io/genact/?module=terraform

Would you like to take a look at this? I do admit I didn't test this in the web before merging it.

**Comment by svenstaro** [comment]
I took a few minutes to look at this and fixed it. :)

**Comment by taskinen** [comment]
Thank you @svenstaro! Looks like it is working now!

I tried looking at it first, but I didn't know what was wrong so I opened an issue. Good work fixing it 👍
