### ISSUE TITLE
Missing line break

### ISSUE THREAD

**Issue by codenyte** [svenstaro/genact#657]
![](https://github.com/svenstaro/genact/assets/39193783/61f8d659-99d6-4d81-8a39-f2d7eb7aa5b9)

I think there should be a link break after `TASK [archive : set up nginx] **************************************************`

**Comment by svenstaro** [comment]
Hey, thanks for the report. Would you like to fix this?

**Comment by svenstaro** [comment]
Feel free to reopen if this reoccurs. :)
