### ISSUE TITLE
Recognized as malware by SentinelOne

### ISSUE THREAD

**Issue by vipau** [svenstaro/genact#661]
As soon as I try to download the MacOS build of this software, it gets blocked by SentinelOne.
This antivirus/antimalware doesn't usually have false positives, and this is the first detection I ever got on anything.

**Comment by svenstaro** [comment]
Can you try to build it yourself exactly the way it's built by CI and see whether you get a detection? I suppose upx is the culprit here as it's sometimes used for hiding malware.
