### ISSUE TITLE
Reimplement old module: bruteforce

### ISSUE THREAD

**Issue by svenstaro** [svenstaro/genact#7]
https://github.com/svenstaro/genact/blob/f408ec25fe69eae33a899ee20818b7c10a38b824/genact/modules/bruteforce.py

**Comment by equal-l2** [comment]
I'll take this.

---

By the way, I'm participating Hacktoberfest.
To make my contribution count, I need your help because Hacktoberfest is now opt-in.
Specifically, I'd like you to add `hacktoberfest` to this repo.

**Comment by svenstaro** [comment]
Ok cool, added the tag.

**Comment by svenstaro** [comment]
You don't have to reimplement the old module perfectly as is, by the way. It's a silly module so you can be as creative as you like.
