### ISSUE TITLE
Build failed while installing

### ISSUE THREAD

**Issue by palash25** [svenstaro/genact#77]
Hi, completely new to Rust, never even written it, just wanted to try out this tool so I installed it but the build failed with the following error

```rust
   Compiling zoneinfo_compiled v0.4.8
error[E0599]: no method named `copied` found for type `std::option::Option<&u8>` in the current scope
   --> /home/palash25/.cargo/registry/src/github.com-1ecc6299db9ec823/zoneinfo_compiled-0.4.8/src/lib.rs:131:49
    |
131 |         let std_flag = tz.standard_flags.get(i).copied().unwrap_or_default() != 0;
    |                                                 ^^^^^^

error[E0599]: no method named `copied` found for type `std::option::Option<&u8>` in the current scope
   --> /home/palash25/.cargo/registry/src/github.com-1ecc6299db9ec823/zoneinfo_compiled-0.4.8/src/lib.rs:132:44
    |
132 |         let gmt_flag = tz.gmt_flags.get(i).copied().unwrap_or_default() != 0;
    |                                            ^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `zoneinfo_compiled`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `exa v0.9.0`, intermediate artifacts can be found at `/tmp/cargo-installLu1JlG`

Caused by:
  build failed
```

Cargo version: 1.32.0
OS: Ubuntu 16.04

Wanted to know if someone else has faced this issue before and ways to solve this.

**Comment by svenstaro** [comment]
Can you update your Rust? You can use rustup to get an up to date version. The cargo version you have ist pretty old so I'm sure your rustc version probably also is.

**Comment by svenstaro** [comment]
Keep in mind that if you only want to use this but not compile it, you can always just download the precompiled binary or use the web version. Compiling it is only necessary if you plan on developing it. Of course it'd be great if you contributed something. If you decide to do so and need help, I can mentor you a bit.
